// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7NjdfGI2ZLwuF0OThhSJygfjFAtEn9E',
    appId: '1:166422488084:web:c4982f14ee2248ea4cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    authDomain: 'buildapplications-27ce1.firebaseapp.com',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    measurementId: 'G-6N8YEVB8L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGQ9iFrsGekooi3zjRiT1VMSC3Ht_37I',
    appId: '1:166422488084:android:b0e04dad4fa05e4b4cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    storageBucket: 'buildapplications-27ce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1OjknSOPGSM6aNoFmcLBngOC7fMD2qLw',
    appId: '1:166422488084:ios:723cf585bb259a884cb301',
    messagingSenderId: '166422488084',
    projectId: 'buildapplications-27ce1',
    storageBucket: 'buildapplications-27ce1.appspot.com',
    iosBundleId: 'com.example.codingTracker',
  );
}
